### ISSUE TITLE
Update blocks

### ISSUE THREAD

**Issue by xxFLORII** [alvin0319/libItemRegistrar#2]
Some items like a fishing rod are update blocks in the inventory

**Comment by xxFLORII** [comment]
Code: https://pastebin.com/iRwBpJPq

**Comment by alvin0319** [comment]
can you provide more info?

**Comment by xxFLORII** [comment]
I have registered the item as shown in the readme. However, instead of the selected item, I just get an update block in my inventory. ( https://pastebin.com/b122gypE )

In addition, the server crashes after a few minutes. ( https://pastebin.com/NysCMYmg )
